### ISSUE TITLE
Package generator in flatdata-rs crate (crates.io)

### ISSUE THREAD

**Issue by VeaaC** [heremaps/flatdata#106]
So that users can easily run the generator in their build.rs?

@gferon @boxdot

**Comment by gferon** [comment]
I had a look, and it's only possible if we copy the required files there before packaging. I believe this can be done in a `build.rs`. I can have a look.

**Comment by gxtaillon** [comment]
If you have pipenv you can install flatdata-generator run `pipenv run which flatdata_generator` and pass the output as generator_path from the example build.rs

**Comment by VeaaC** [comment]
It might at least no harm: E.g. making the path optional, and trying to auto-discover it in case it has not been specified.

I am also thinking that it would be very neat if we could package it in a way that the user does not need to install anything (maybe not even python?), e.g.: https://github.com/indygreg/PyOxidizer

Then we would have one package for using flatdata (flatdata), and one for generating files (flatdata-generate?).

**Comment by gxtaillon** [comment]
Yeah it would make it easier to get started.
I would love a package on crates so that `cargo install flatdata-generator` becomes possible, with the build file picking it up automatically and maybe even creating the source/target folders at a default location.

**Comment by gferon** [comment]
This is actually a good idea @gxtaillon. I'll give it a go to see how it turns out.

**Comment by gferon** [comment]
@gxtaillon we just published v0.3.1 of `flatdata` on [crates.io](https://crates.io/crates/flatdata/0.3.1) with a helper function for `build.rs` scripts that should help you. Could you give it a go?
