### ISSUE TITLE
Build image automatically from `ci/Dockerfile` on each update of the file

### ISSUE THREAD

**Issue by boxdot** [heremaps/flatdata#11]
This is needed since right now, the docker image is stored under my account, and so cannot be controlled by other flatdata maintainers.

**Comment by VeaaC** [comment]
Related news: https://developer.github.com/changes/2018-04-25-github-services-deprecation/

**Comment by boxdot** [comment]
@VeaaC: Thanks. I will try to find a corresponding app.

**Comment by gferon** [comment]
Since now all implementations are separate, I would ditch the Dockerfile altogether and just use what Travis CI gives us.
