### ISSUE TITLE
Publish 0.3 to crates.io

### ISSUE THREAD

**Issue by VeaaC** [heremaps/flatdata#143]
0.2 still has multiple issues (lifetimes, etc), so it would be nice to update to the latest version.

Also: Can we set it up that it is either done:
* automatically
* or a group of people can do it
?

**Comment by gferon** [comment]
I believe in crates.io it is possible to share publish permissions on a crate. @boxdot ?

**Comment by boxdot** [comment]
Yes, it is possible. I added you to the project as owners. crates.io told me that an invite is sent out. If you do not receive anything, I guess, you need to login at crates.io for the first time.
