### ISSUE TITLE
Simplify importing flatdata-rs

### ISSUE THREAD

**Issue by boxdot** [heremaps/flatdata#150]
At the moment, to import flatdata in rust, we need to write:

```rust
#[macro_use]
extern crate flatdata
```

* We should try to remove this requirement.
* Also, nightly compiler fails due to missing `flatdata_intersperse` macro.

**Comment by gferon** [comment]
For the second point, see: https://github.com/rust-lang/rust/issues/63888

**Comment by VeaaC** [comment]
Is this still an issue?

**Comment by boxdot** [comment]
Yes, minimal example:

```rust
#[macro_use]
extern crate flatdata;

include!(concat!(env!("OUT_DIR"), "/graph.rs"));

fn main() {
    println!("Hello, world!");
}
```

Looks like there is also a bug in the docs which tell to do:

```rust
#![allow(dead_code)]
include!(concat!(env!("OUT_DIR"), "/graph.rs"));
```

but the dead code annotation actually does not work.
