### ISSUE TITLE
Implicit bind of vector and multivector fails

### ISSUE THREAD

**Issue by boxdot** [heremaps/flatdata#17]
When trying to bind implicitly a vector and a multivector the generator fails. Example:
```
@bound_implicitly( characters: vertices, character_data )
archive Graph {
    vertices : vector< Character >;
    character_data: multivector< 32, Nickname, Description >;
}
```
Error:
```
12:41:29 - CRITICAL - app:67 - Error reading schema: Referring to incorrect type. Expected <class 'generator.tree.nodes.resources.vector.Vector'>, actual <class 'generator.tree.nodes.resources.multivector.Multivector'>
```

Is this expected? As far as I understand, it should be possible to bind both. In my example, I am referencing the elements of vertices and character_data with the same index.

A small sidenote: probably, the error should also refer to the line in flatdata's source, instead of the line in the source code of the generator.

**Comment by VeaaC** [comment]
It's a limitation of the generator (see bound_resource.py):

```
    def _create_references(self):
        return [VectorReference(name=r) for r in self._resources]
```

Should most likely be fixed to be a generic ResourceReference, or a reference to things that are index-addressable (everything except RAW I think)

**Comment by imagovrn** [comment]
Please see the comment in the PR #18.
