### ISSUE TITLE
Expose maximum possible value for primitive types in generated code

### ISSUE THREAD

**Issue by gferon** [heremaps/flatdata#185]
While playing with flatdata, I realized that if you encode a primitive field with a custom size like so:

```
struct Attribute {
    value : u32 : 3;
}
```

then in the generated code, the number of bytes of the field is not exposed anywhere.

This could be useful for example when adding a `static_assert` in C++ that internal enum values match the size of the field. I suppose in Rust, we could also leverage this for some safer fun!

What I would have to do now:

```cpp
static_assert( ::MyEnum::COUNT == 8, "Oops, make sure your flatdata schema is up-to-date!" );
```

what I'd expect:

```cpp
static_assert( ::MyEnum::COUNT == something_max_value(), "..." );
```

pinging @boxdot and @VeaaC to discuss the proposal before I get to the implementation!

**Comment by VeaaC** [comment]
In C++ this should be easy: Just add as a method to the `Member` class (e.g. max()/min())

In Rust it is a bit more tricky, we have getter methods for each member, but they directly return the target type.
 The only thing I could think of would be additional getters with naming conventions, e.g. `xyz_max()/xyz_min()`. This could theoretically clash with names defined by the user.

@gferon are you going to do a C++ implementation?

**Comment by VeaaC** [comment]
Maybe this could even be generalized: How about enabling compile-time reflection over the schema? E.g.:
* check if new resources were added to an archive (e.g. to static_assert that something needs to be done)
* check min/max values
* check possible enum values
* etc?
