### ISSUE TITLE
Publish on PyPI

### ISSUE THREAD

**Issue by deeplook** [heremaps/flatdata#193]
Because now there is https://pypi.org/user/heremaps.

**Comment by VeaaC** [comment]
Already exists:
https://pypi.org/project/flatdata-py/
https://pypi.org/project/flatdata-generator/

**Comment by deeplook** [comment]
I had not found a link from https://github.com/heremaps/flatdata to https://pypi.org/project/flatdata-py/
or https://pypi.org/project/flatdata-generator/. They also don't appear under https://pypi.org/user/heremaps/. Maybe it's worth adding this user as maintainer or owner?
