### ISSUE TITLE
C++ library: Add class owning memory for a single mutable struct

### ISSUE THREAD

**Issue by VeaaC** [heremaps/flatdata#22]
flatdata supports sorting single structs in an archive (usually headers). Currently those are generated/written in C++ by creating a ``flatdata::Vector< T > v( 1 );```. Adding a class that represents this concept more closely would be more intuitive/readable.

Proposal:
- Add a ```template< typename T > flatdata::Struct{ ... }``` for this concept

**Comment by boxdot** [comment]
Closing since it was resolved in #24.
