### ISSUE TITLE
Define supported & tested target platforms

### ISSUE THREAD

**Issue by gferon** [heremaps/flatdata#26]
I think it might make sense to test multiple platforms in CI, in-order to be able to support them officially and make sure it builds correctly.

I suppose testing on Ubuntu LTS 16.04 and CentOS 7 would already be enough to begin with.

**Comment by boxdot** [comment]
I think this makes totally sense. I think that we also should build on both platforms with clang and gcc. Futher, it would be nice to use a bleeding edge compiler, however, to allow failures when using it. This would allow us to find bugs and warnings faster and also to prepare for the future changes.

So, if I am not mistaken, the matrix looks right now like that:
* [ ] Ubuntu LTS 16.04 + gcc Version ???
* [ ] Ubuntu LTS 16.04 + clang Version ???
* [ ] CentOS 8 + gcc Version ???
* [ ] CentOS 8 + clang Version ???
* [ ] Some system + gcc 7
* [ ] Some system + clang 5

**Comment by gferon** [comment]
The latest stable CentOS ships with GCC 4.8.5, with the possibility to add GCC 5.3, 6.2, 7.2 and clang 4.0.1.

Ubuntu 16.04 (xenial) ships with GCC 5.4, and 18.04 (bionic) will ship with GCC 7.2 in April. Both Ubuntu versions have official packages for clang 4 and 5.
