### ISSUE TITLE
Make unittesting more stable

### ISSUE THREAD

**Issue by boxdot** [heremaps/flatdata#28]
Right now, `make test` is not working if `make` was not executed before. This is due to the limitation of downloading the external project and needs to be fixed.

I would like also use the opportunity and a start a discussion about changing the unit testing framework. Our unit tests are fairly simple and do not require mocking, so we don't have use for GMock. On the other hand, GTest needs to be downloaded and built. Which is ok for external dependencies that are really needed for the library, but is cumbersome for unit testing which should just work out of the box. 

I propose to either:

1. Integrate GTest into our source code, or
2. To use something less heavy like [Catch2](https://github.com/catchorg/Catch2).

The latter is a header only single file unit testing library which has proven for me to work already many times.

What do you think, @imagovrn, @VeaaC?

**Comment by imagovrn** [comment]
@boxdot I agree, why not :+1:
