### ISSUE TITLE
Generator: Add support for multiple output files

### ISSUE THREAD

**Issue by imagovrn** [heremaps/flatdata#5]
Add support for multiple output files especially to python generator, to output proper package with respected namespaces. Adapt CMake for easier integration into C++

**Comment by boxdot** [comment]
I prefer to have a single output file. The rationale is that the code is generated and therefore - not really meant for human editing. Splitting code in multiple files is usually done to enable people to work on different independent parts, i.e. it implies better maintainability. The latter is not important for generated code.

In case of python, they made an unfortunate decision to bind modules to the filesystem.

**Comment by VeaaC** [comment]
We do not support including other files at the moment, so closing until this is needed
