### ISSUE TITLE
Strategy for closing when destructing ExternalVector (MultiVector).

### ISSUE THREAD

**Issue by boxdot** [heremaps/flatdata#66]
Behavior right now: When `ExternalVector` is destructed, we have a debug assert, that the user has closed it. Same for `MultiVector`.

In situation, when a user has multiple resources (that need to be closed) encounters an error and wants to make an early return, the resources are destructed, which terminates the program in debug mode. This is obviously not perfect. We should rather try to close in the destructor. The problem is, that closing may fail and we have two possible strategies what to do then.

1. On failure inside close, fail hard. This will terminate the program, since we are failing in a destructor.
2. On failure inside close, do nothing (except for producing a log message).

I tend to use the second approach. Our contract specifies that the user should close resources explicitly. Otherwise, we just try to do it for her, and when we can't do it, we don't want to kill the whole program. This also follows the practice in https://doc.rust-lang.org/std/io/struct.BufReader.html.

@VeaaC, @imagovrn: If you agree, I would implement this.

**Comment by VeaaC** [comment]
C++ and Rust just silently swallow such errors, so we might want to do the same.
