### ISSUE TITLE
Annotations for vectors with sentinels

### ISSUE THREAD

**Issue by VeaaC** [heremaps/flatdata#73]
Oftentimes flatdata vectors contain a sentinel in the end. It is easy to forget excluding it when iterating.

One idea would be to add an annitation ```@sentinel``` that the generator could use to create two getters for the archive:
* ``` get_xyz() const``` and ``` get_xyz_with_sentinel() const```

What do you think @boxdot @imagovrn ?

**Comment by boxdot** [comment]
I like the idea a lot. I think we should implement it.

**Comment by VeaaC** [comment]
I would not be backwards compatible to add support to language one-by-one, so either we need to:
- Fail schema compilation if not supported
- Implement all language immediately

**Comment by VeaaC** [comment]
I am currently more in favour of implementing another field type (range?), that would automatically mark every vector containing such a struct as having a sentinel, and making it impossible to use such struct in multi_vector.

Would we have use for sentinel annotation beside the range use-case?

**Comment by boxdot** [comment]
Personally, I think that having a sentinel annotation as documentation is already a big plus. Knowing our internal use cases, it is sometimes pretty hard to figure out if a vector is using a sentinel or not. Similarly to implicit bounds and references annotations sentinels annotations would improve readability.

I would still like to hear an opinion from @imagovrn.

**Comment by VeaaC** [comment]
Closing for until. #131 added support for ranges + sentinel.

When we have a use case for sentinels without ranges we can re-open.
