### ISSUE TITLE
Migrate Github services

### ISSUE THREAD

**Issue by VeaaC** [heremaps/flatdata#74]
See https://developer.github.com/changes/2018-04-25-github-services-deprecation/

**Comment by boxdot** [comment]
Right now, we are using 2 services:

* Docker hub
* Travis CI

The latter is also installed as an app. So, I guess it is safe to delete it. Regarding Docker, we wanted to use it for automatic build of dev images (which are used for testing in CI), but we never started to do it. So, it should be also ok to delete this one.
