### ISSUE TITLE
Create centralized list of flatdata testcases

### ISSUE THREAD

**Issue by VeaaC** [heremaps/flatdata#96]
Since we now have 4 languages, and each has it's one schemas for tests, I was thinking we should maybe create a central place for testcases:
* for each feature of flatdata a sample schema
* for each corner cases a sample schema
* each with a comment describing what should be tested

That would make it easy to test compliance for new language implementations, and reduce redundancy of the tests.

Opinions @boxdot @imagovrn @gferon ?

**Comment by boxdot** [comment]
This makes totally sense. As you said it makes sense to have a schema for each feature. Then every language can implement an integration test per schema, using generator to generate the corresponding builder/reader. This btw would also allow easily to create a feature matrix.

**Comment by VeaaC** [comment]
Implemented in #99
